### ISSUE TITLE
Support more characters in remap

### ISSUE THREAD

**Issue by laurigates** [WootingKb/wootility-issues#120]
I would like to be able to use the remap feature to map the ä & ö characters to something.

I got the keyboard with the US ANSI layout as it's more convenient for me in all other cases except when typing in my native language. The only thing I'm missing are the ä & ö characters.

At the moment I'm using layout switching in Windows, but I think it might be more convenient to be able to just map those characters to Fn+A and Fn+O or something. Actually it would be neat if it was possible to map the umlaut character to something as well, that would bring additional possibilities on how to deal with this 😄 

I tried the United States-International layout in Windows' keyboard language settings, but I really don't like how it makes the quote key (among others) into a dead key.

### Additional information
**Platform information**
Windows 11

**Wootility and Firmware version**
Wootility v4.2.2-beta
Firmware v2.3.2

**Keyboard Type**
Wooting Two HE ANSI United States

**Comment by simon-wh** [comment]
Hi, I understand wanting those characters but unfortunately, it's not something that can really be added to remap. As you noticed with layout switching in Windows, you can change the characters the keyboard inputs without changing anything on the keyboard, this is the nature of how different languages work with keyboard input. Pretty much every single language of a keyboard technically sends the same information to your PC, it's just up to your PC, given the selected language to convert that into the appropriate character for your language.

I imagine that it's theoretically possible to input them using Unicode inputs, Alt + X + 4 numbers but that is something that isn't really possible to add into the current remap system (although now that I think about it, I could look into trying to implement it as an alternative type of DKS item but that's something for the future). That being said, your first line of attack is to try and enable it through your system language, I had a quick google and found some options for creating custom keyboard language layouts in windows so that may be an option for you to go. Additionally, you could potentially try using AutoHotKey and make use of the F13-F24 binds to enable additional inputs

**Comment by nullbyto** [comment]
I'm a ANSI keyboard user which uses Umlaut characters as well. The best solution in my experience is to use this layout which is amazing, you can download from: [](https://eurkey.steffen.bruentjen.eu/)
Which with the combination of Altgr + character gives the umlaut of it. It is for european languages.

For example: 
Altgr + a = ä
Altgr + shift + a = Ä
Altgr + u = ü
...

**Comment by laurigates** [comment]
> I'm a ANSI keyboard user which uses Umlaut characters as well. The best solution in my experience is to use this layout which is amazing, you can download from: Which with the combination of Altgr + character gives the umlaut of it. It is for european languages.
> 
> For example: Altgr + a = ä Altgr + shift + a = Ä Altgr + s = ß ...

Sounds interesting, but the link is missing 😄

**Comment by laurigates** [comment]
> > > I'm a ANSI keyboard user which uses Umlaut characters as well. The best solution in my experience is to use this layout which is amazing, you can download from: Which with the combination of Altgr + character gives the umlaut of it. It is for european languages.
> > > For example: Altgr + a = ä Altgr + shift + a = Ä Altgr + s = ß ...
> > 
> > 
> > Sounds interesting, but the link is missing 😄
> 
> My bad i forgot to add a text for the link. I just fixed it.

Thanks, this is the perfect solution for me!  😄
