### ISSUE TITLE
Like to have a dedicated A0 button to always force to select the digital profile without toggling.

### ISSUE THREAD

**Issue by ZebonianJustice** [WootingKb/wootility-issues#124]
I don't like to toggle between analog and digital with the mode button so i would like to have a dedicated button for the digital profile.

**Comment by Faxmachinen** [comment]
This could be added as an "A4" key remap so that people who want the toggle function can keep it.

And while we're adding profile switching keys, would it be possible to add keys for profiles A5-A12 on the Two HE? If I understood the marketing materials correctly, even the non-active profiles are saved on the keyboard.

**Comment by simon-wh** [comment]
We just added this as a possible binding, we've called it D1 for now, subject to change. 

it'll be coming with Wootility v4.4, which will be the Wootility version, that's releasing for 60HE in the near future.

**Comment by Faxmachinen** [comment]
Excellent. Thanks Simon!
