### ISSUE TITLE
Key remappings aren't applied until reloading the profile

### ISSUE THREAD

**Issue by samblouir** [WootingKb/wootility-issues#135]
**Describe the bug**
Remapped keys aren't changed until the user switches to a different profile and returns to the changed profile.

"Save to Keyboard" still requires profile switching. This is unlike other behavior in Wootility, where changes are applied immediately.

**To Reproduce**
1. Create an Analog Profile with at least one Unlinked Remapped Key
2. Go to any Analog or Digital Profile
2. Click Remap keys
3. Remap a key
4. The keyboard uses the previous mapping and doesn't load the new mapping until the profile is reloaded
5. Sometimes hitting "Save to Keyboard" immediately applies the new mapping without requiring a reload

**Screenshots / Video**
The "G" and "U" keys are both set to "F16"
![image](https://user-images.githubusercontent.com/13413126/150009937-3a4d5b09-cf98-4192-90a3-fa16a8a0e20f.png)

xev shows the keycode 194 appearing when pressing "U", but not "G".
![image](https://user-images.githubusercontent.com/13413126/150009851-94978344-5ac5-47e3-81bb-b2debf488637.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Wootility and Firmware version**
Wootility v4.3.5-beta
Firmware v2.4.6

**Keyboard Type**
Wooting Two HE English

**Comment by mmahmoudian** [comment]
I cam here to report this and found this issue. in my case the remap didn't get applied, but I realized pressing the "Save to keyboard" again get it to work.


My system info:

>```
> Wootility v4.3.5-beta
> Wooting Two HE
>   '- Firmware v2.4.6
> System:
>   |- Distro: Manjaro Linux
>   |- Kernel: 5.15.12-1-MANJARO x86_64
>   |- bits: 64
>   '- Desktop: KDE Plasma 5.23.4 
>```

**Comment by simon-wh** [comment]
Hi guys, thanks for the report. 

Currently, the behaviour is a little unexpected due to pretty much every other setting automatically applying to the keyboard without needing to click "Save to keyboard". Remap is the one exception where due to the nature of how remap works it's not possible to get it to temporarily apply before saving. 

So right now the expected behaviour is that as soon as you click save to keyboard after editing remap it should be all applied. That makes the main premise of this issue a bit more of an "enhancement" I guess, as this requirement should be communicated in the UI better given its behaviour is non-standard compared to the rest of the configuration. 

@samblouir You mentioned that you had cases where saving didn't apply remap, could you potentially do some testing to see if that's a reoccurring issue given the basis that clicking save is necessary for remap to be applied?

**Comment by DarrenVs** [comment]
From my testing; this issue is specific for the Fn-layer(s), and only occurs for the first time you unlink the remapping on that profile.
Once switching back and forward between the profiles, the Fn layer(s) update as expected (after pressing Save to Keyboard).

The problem seems to be that the Fn layer(s) do not receive the changes after unlinking the profile until the profile is reloaded.

**Comment by mmahmoudian** [comment]
What @DarrenVs mentioned seems very consistent with my experience.

**Comment by simon-wh** [comment]
Thanks for the additional information, digging into this now

**Comment by simon-wh** [comment]
A fix for this has been implemented and will be available in the next firmware update, likely to be v2.4.10
