### ISSUE TITLE
Some keys seem to be useless on Mac OS

### ISSUE THREAD

**Issue by codysechelski** [WootingKb/wootility-issues#143]
**Describe the bug**

**To Reproduce**
1. On a Mac
2. [](https://keyboardchecker.com/) 
2. Click the PrtSc key
3. Observe that nothing is registered

**Screenshots / Video**

**Desktop (please complete the following information):**
 - OS: macOS Montery

**Wootility and Firmware version**
v4.2.2-beta

**Keyboard Type**
Wooting 2HE (US English)

I suspect this is just Mac being Mac and not really a bug but I thought I would double-check. I have a thunderbolt docking station and I am constantly switching between my Mac, Windows, and Linux Laptops. It drives me nuts that I can use some keys like `ins` and `PrtSc`. I was hoping that the Wootility would be able to help me map those keys to something useful like causing the `PrtSc` to actually take a screenshot.

But it appears that macOS doesn't respond at all

**Comment by simon-wh** [comment]
As you mentioned, this is kinda just a Mac thing, you'll need to either find a way to bind e.g. PrintSc to an action inside MacOS or, alternatively you could do a DKS binding like this to perform the standard Mac screenshot shortcut
![image](https://user-images.githubusercontent.com/10797576/154996989-037e4de8-f276-435d-ad00-fee2a0b8305e.png) 

If you were to go the DKS route you could have your Mac profile on Analog Profile 1 and your Windows/Linux profile on Digital Profile. In my case I use this strategy for swapping around Win/Alt so that on Mac the Command/Option are in the expected position (I have used the built in keyboard modifier mapping thingy that you can use to swap but that caused weird behaviour with global hotkeys for me), but still getting the standard Win/Alt positions when on Windows/Linux

Outside of this case, it's to be expected that not all keys available to be bound will work, mainly looking at keys like "Open Calculator". These are added on the basis that it is useful on at least one of our supported platforms, so are not guaranteed to work on all as each OS has it's own set of keys that it actually does something with

**Comment by codysechelski** [comment]
Sorry, it's taken a while to get back to you. You're a genius @simon-wh ! This works perfectly! Thanks!
