### ISSUE TITLE
Analog will stop working after a few days

### ISSUE THREAD

**Issue by DarrenVs** [WootingKb/wootility-issues#15]
## Describe the bug
Every few days after starting my computer, the analog output will not work. This problem will consistently return, no matter what fixes we have attempted in Discord. The only solutions so far have been resetting all keyboard settings or factory resetting.

The best workaround has been to backup all the active profiles and press the **Reset all Keyboard settings** button.

## To Reproduce
1. Have a profile that makes use of the analog settings
![image](https://user-images.githubusercontent.com/2780639/73908384-c5987f80-48a9-11ea-90dc-2f3890ecda52.png)
2. ... *(Maybe a pc crash. When it does happen analog will be broken like this until you reset settings)*
3. Notice after starting up your computer that the analog controls do not work

## Screenshots / Video
**(Click for video controls)**
[![Click for link to imgur](https://user-images.githubusercontent.com/2780639/73908107-e4e2dd00-48a8-11ea-9260-c00d7b850399.gif)](https://imgur.com/HRCt0H2)
*In this video I demonstrate trying to make use of the analog feature, showing it is not working. And then proceeding to do my workaround to fixing it.*

## Desktop
 - OS: Windows 10
 - Happened on USB 2.0
 - Motherboard type: `GIGABYTE 970A-DS3P`

## Wootility and Firmware version
- Wootility version: `3.3.3`
- Frimware version: `1.27.3`

## Keyboard Type
Wooting one + English

**Comment by PastaJ36** [comment]
Weird, wonder what part of the reset makes it work again. The reset reboots the keyboard, but I assume replugging doesn't fix the issue right?

**Comment by Rocky04** [comment]
So I bet this problem only happen to him when he selects an analog profile with XInput and then reboot the PC. Normally the device should be resettet multiple times during a reboot but if this didn't happen the XInput interface can be in a deadlock. 

I can reproduce this behaviour by using a VM, if the keyboard is pass though to the guest and the guest is rebooted while an XInput profile is active. I had discussed this a long time ago. I assume the reason is that the buffer gets quickly filled if the interrupts aren't handled fast enough, because the Wooting sends data for XInput each intervall indead only after the values are changed. I can even repoduce this behaviour with an original Xbox 360 controller, it only takes longer to reach the deadlock state.

**A short attempt would be to only provide values if the values have changed, but I guess the real problem is how the Wooting handles the USB interrupt, but this is much harder to address.**

**Comment by DarrenVs** [comment]
This issue persists through reboots of the computer, and I believe re-plugging the keyboard (will come back on this when i can test it again).
Last time we tried to debug this we ended up on me not having the hardware to properly debug the issue and blaming windows for it as the best conclusion

**Comment by Rocky04** [comment]
Later on I was able to reproduce the problem and had a deeper look into it. The mentioned discussion was with Jeroen only.

The software reset though the Wootility forces the Wooting to be reconnected like Jeroen menioned with its default settings. So it's like a replug, meanning it shoud also after that.

As I had indicated above, if the reboot causes the problem for you because the Wooting isn't resetted during it, then there is no way what another reboot can fix it.

**So please try to reproduce the problem by following the process I post before.**

**Comment by DarrenVs** [comment]
I got te bug again, no clue what produced it.
After restarting my PC analog worked again. So I assume Rocky's theory is right

**Comment by Rocky04** [comment]
**The question is if you can force the bad state by follwing the posted sequence from me above...**

**Comment by Rocky04** [comment]
I have looked into this again...

To me it seems the OS has problems if it gets spammed with data. When I passthrough my Wooting to a VM with VMware and start spamming normal keys on boot Win 10 can't register normal keypresses. Then I don't see any data with Wireshark for the keyboard intefaces. After a reboot without pressing anything it works again.

As already mentioned, if an analog profile is active while rebooting the OS can't detect the Xbox inputs anymore. If then the OS is rebooted while no analog profile is active set to type XInput it will work again.

I only wasn't able to break the classic controller at all. Because everything was working again after a reboot when I don't trigger it, because of that I think an overfilled buffer from the OS is maybe causing it. Haven't tested it on Linux yet...

**Comment by DarrenVs** [comment]
Replugging the keyboard has resolved this issue for me every time

**Comment by PastaJ36** [comment]
@DarrenVs Are you still experiencing this with the latest update?

**Comment by DarrenVs** [comment]
> @DarrenVs Are you still experiencing this with the latest update?

@PastaJ36 Haven't had my windows update or pc crash since the alpha build.

I don't think it's worth keeping this issue open though as the cause is rare, problem is probably unavoidable, and the solution is pretty simple.
I believe most people that run into this solve it through the 'Reset_Xinput_driver' guide thanks to the Gamepad Tester debugging info, which I find a sufficient enough solution to this problem.

Next time (if it can still happen) I can let you know so we can gather more info on it to see if this is solvable or not
