### ISSUE TITLE
Fn Layer 2 reappears after reconnecting keyboard

### ISSUE THREAD

**Issue by Duckleeng** [WootingKb/wootility-issues#200]
Bug description:
After disconnecting the keyboard and reconnecting it back, the Fn Layer 2 gets added back to the Digital profile (all though it was previously deleted and the profile was saved).
The RGB Sleep Mode also gets reverted to default settings.

1. Delete Fn Layer 2, save profile, disable RGB Sleep Mode
2. Disconnect keyboard from PC
3. Reconnect keyboard to PC
4. The Fn Layer 2 is back, and RGB Sleep Mode is enabled again

OS: Windows 10

Wootility and Firmware version:
Wootility v4.5.0
Firmware v2.6.13

Keyboard:
Wooting 60HE ARM

**Comment by Uiasdnmb** [comment]
I also noticed this and I'm not sure if it should go into separate issue but when I delete that FN2 layer mapping it triggers removal of FN1 layer colors.

**Comment by DuckI1ng** [comment]
NOTE: RGB Sleep Mode doesn't reset if Fn2 layer isn't deleted

**Comment by Kallestofeles** [comment]
Bump on this issue.
I have deleted FN2 layer button mapping from the bottom right "Fn" button deliberately for a specific use case and every time I open up Wootility to re-map, tweak or check for updates, FN2 layer keeps coming back. (PC has been off from time to time so for the keyboard it seems like it has been disconnected)
Even when I simply disconnect and reconnect the keyboard as the OP mentioned, FN2 layer keeps coming back, even though I remove it and save the changes to keyboard.
No button on the keyboard nor on Layer1 is mapped to FN2 layer.

What is saved to keyboard and how it should remain:
![image](https://github.com/WootingKb/wootility-issues/assets/3207177/14fb930b-2943-4ecf-9ce4-33b3eb3b3b31)

How it actually comes up whenever Wootility is started after the keyboard has disconnected from the PC (turning off the PC and letting keyboard shut down counts as well to be extra annoying):
![image](https://github.com/WootingKb/wootility-issues/assets/3207177/6c38abe0-c3b8-4b33-9400-8c319b83b9ba)

Just to ensure clarity:
The issue is NOT with the MAIN LAYER - that one remains intact as it should. The issue is that the bottom right button on the keyboard (labelled "Fn") keeps resetting on the FN1 Layer - and Fn Layer 2 keeps returning from the grave, even though I remove it every time I open Wootility and Fn2 accessing button it is not mapped to anything on the keyboard.

In case more info/debugging is needed, I am more than happy to provide details.

Wootility v4.5.5 (Desktop)
OS: Windows 11
Device: Wooting 60HE ARM, v2.6.22

**Comment by Kallestofeles** [comment]
Polite *bump* on the matter. It still exists and is annoying.
Happens on both web and local versions of Wootility.

**Comment by xaizone** [comment]
Same issue, happens on any OS and Wootility "version" when you replug the keyboard. Reproducible every time on my Wooting 60HE AVR.

**Comment by Duckleeng** [comment]
I see that this issue has been closed 2 months ago, I can still consistently replicate it though. Also, I'm not sure if it was clear, but the issue only happens on the Digital Profile, Analog Profiles work as expected (Fn Layer 2 stays deleted).

Wootility v4.6.16
Wooting 60HE ARM
Firmware 2.7.2

**Comment by xaizone** [comment]
> I see that this issue has been closed 2 months ago, I can still consistently replicate it though. Also, I'm not sure if it was clear, but the issue only happens on the Digital Profile, Analog Profiles work as expected (Fn Layer 2 stays deleted).
> 
> Wootility v4.6.16 Wooting 60HE ARM Firmware 2.7.2

Hey, fix seems to be already present in Beta Wootility, more here: https://github.com/WootingKb/wootility-issues/issues/276#issuecomment-1978417313

You can try out the beta firmware by following Simon's guide below:
1. Enable access to test builds by going to https://wootility.io/?test-builds=true (or https://beta.wootility.io/?test-builds=true)
2. Make sure your keyboard is connected
3. Go to Settings -> Updates
4. Under your device, press "Get Test firmware"
5. Once it loads, select 2.7.2-test.beta6.1
6. Install update
