### ISSUE TITLE
"This layer switch key is configured from Fn Layer x" unecessary when Fn layer is locked.

### ISSUE THREAD

**Issue by DeadlockOfDeath** [WootingKb/wootility-issues#243]
When the Fn Lock key has been used to lock an Fn layer, the Fn button used to get to that layer should be able to be mapped to a different key.

**I want to get from the Main Layer**
![Fn 1](https://github.com/WootingKb/wootility-issues/assets/133504785/85644dc8-60db-4baa-b3ea-329fc54f8a29)
**and lock into Fn 3**
![Fn 3](https://github.com/WootingKb/wootility-issues/assets/133504785/8121ed6e-b00e-49c2-b519-fa113f480c7e)
**This is how I want to do it**
![Method](https://github.com/WootingKb/wootility-issues/assets/133504785/11350cdc-b7e9-41f0-addc-826480c7dc2c)
**It wont let me use the left arrow key, even when the layer is locked**
![Unfortunate](https://github.com/WootingKb/wootility-issues/assets/133504785/92bdf5e8-85c3-4745-807d-60272b7fd2f4)

My Experience:
I got my 60HE today, switching over from my previous 2HE. It is my first 60% keyboard and I have been in the wootility for hours transfering my old setup from the 2HE. The biggest anoyance is figuring out what to do about the arrow keys. Long story short, I came up with the most awesome solution in my head, tried to impliment it, and found that I am blocked by "This layer switch key is configured from Fn Layer 2". It is not too big of a deal, I can always put the Fn 3 somewhere else, but somewhere else would not be nearly as elegant and would require more hand-movement that I know in my heart can be reduced. 

The Profile in Question:
e85adfd05d92f7f6e267edff6a8b338961c7

Wootility v4.5.5
Wooting 60HE ARM

**Comment by BigBrainAFK** [comment]
I think the main issue is that before you lock FN layer 3 the key has to be on fn layer 2 and 3 so that when you hold fn3 it doesnt go back to another layer. If there is no FN3 on a non locked layer it would basically not be able to hold FN3 thus you couldnt even lock it to begin with. Simon might know more but I think that is the main issue with layer switching in general. You need the key you wanna hold on the same layer as it otherwise wouldnt be held anymore.

**Comment by DeadlockOfDeath** [comment]
What do you mean by "so that when you hold fn3 it doesnt go back to another layer"? My problem is Fn 3 being on the locked layer not on the non locked layer, I am kinda confused.
The way I see it is different from yours in that I see it as the Fn 3 button being on the Fn 2 layer not on both layers at once. The reason for why the Fn 3 button is normally inaccessable in the Fn 3 layer even though its on the Fn 2 layer is usually because the button is being held down otherwise you couldn't get to the layer. My opinion is that this makes sense when this is guaranteed but that is not always the case. For example, what if you have multiple Fn buttons to get to a layer? I am willing to sacrifice the ability to map the button that I am holding to get to the layer, but what about the other fn button I could have used? This is what I want to be implimeted. 

Look at what you are making me do:
![why](https://github.com/WootingKb/wootility-issues/assets/133504785/f7c3e955-6daf-48c0-952f-6d08a0d8d755)
I have to sacrifice my backslash and its not a straight line anymore.

**Comment by BigBrainAFK** [comment]
You cant automatically lock a layer and have it be able to unlock as toggle keys dont work. So to lock a layer you need to have the FN Layer + FN Lock on that layer pressed. You cant directly lock an FN layer with just 1 button. So to get to any FN layer youre normally supposed to hold FN, hold another FN button on the FN layer, let go of any previously pressed FN buttons before the last, press FN lock on the layer you wanna lock, let go of all keys. This is meant for things like FN 1 in your images where you have a completely different function set. The way you use FN layer 3 is more something youd use a different profile for especially if you wanna lock it basically most of the time. 

Lets say FN 1 is on Main layer and there is NO FN1 button on the FN layer 1. If you now hold FN1 on main your keyboard goes to FN layer 1, the key you hold is now not FN1 anymore so it goes back to Main layer. Since youre now on Main layer and youre holding the key still it now sees you holding FN1 so it switches to FN layer 1. I hope you can see why there is a need for an unremovable FN1 key on FN layer 1 in this example. This is also the base to what I said before: You need to hold the FN key of the layer youre on for you to even be able to press FN lock. if you go FN1 + FN2 + FN3 + FN Lock you can actually let go of the previous FN key as soon as you hold the new one. So FN1 + FN2, let go of old FN1, FN2 + FN3, let go of FN3, FN3 + FN Lock, let go of all. Then youre still locked in FN3.

**Comment by DeadlockOfDeath** [comment]
I am sure there is a way to program this, somehow. What I explained in my previous comment about the way that I see the layers working is just how I wish it would work, I am sure in the code it is just like what you said where the fn key is in two layers at once. I saying though that if you are able to code advanced keys where you are doing multiple key presses in one stroke I am sure there is a way to press to keys at once in this scenario.

**Comment by BigBrainAFK** [comment]
Well we want to make FN keys able to be used with the advanced toggle key. This MAY result in the restriction being lifted but would add another key to untoggle the layer. Theres just too many edge cases to just be able to remove it from the layer its in. I wont say it wont ever ever happen but I would say its unlikely for now. But its definitely a rather complex issue to solve reliably.

**Comment by DeadlockOfDeath** [comment]
Alright, I wanted to keep it all in one profile but I guess two will have to do for now. Thanks, for considering it.

**Comment by BigBrainAFK** [comment]
Maybe we can get DKS to press a non existing FN layer key and FN lock so you only need the FN lock key on the layer to unlock it. Still feels more like a profile job though in your use case.

**Comment by DeadlockOfDeath** [comment]
I was able to save the backslash by using the advanced toggle key with fn 3 like you mentioned, so I guess my profile is complete now.
fe969852c8168a48ab3ee14df7629564563c

**Comment by BigBrainAFK** [comment]
Just keep in mind youre stuck on that layer then until you reboot the keyboard or switch profiles.

**Comment by DeadlockOfDeath** [comment]
I have just discovered a way to get around the restriction. This may be considered self-snitching but I see it as proof that the restriction is unecesary and not hard to code since it already works. All I did to get around the restriction is just make a dks and put the fn 3 key in it. There is no restriction and it works exactly like it should.

**Comment by BigBrainAFK** [comment]
This is because DKS is handled separately from normal keypresses due to the whole 4 keys and trigger points. while it is a way around it doesnt invalidate the restriction.

**Comment by DeadlockOfDeath** [comment]
I am happy I discovered this exploit so PLEASE DON'T remove it :)

**Comment by BigBrainAFK** [comment]
Not an exploit but a completely different key handling system.

**Comment by DeadlockOfDeath** [comment]
At least pretend that it is, and that I discovered it myself.
