### ISSUE TITLE
Ubuntu 18.04: Wootility can't speak to keyboard

### ISSUE THREAD

**Issue by burito** [WootingKb/wootility-issues#26]
By default, the local user doesn't have permission to read or write directly to the keyboard, so the Wootility can't do anything. Running the following command...
```bash
sudo bash -c "cat > /etc/udev/rules.d/51-wooting.rules" << EOF
ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="ff01", TAG+="uaccess"
ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="ff02", TAG+="uaccess"
EOF
```
...will tell Linux that the local user can have read/write access to the keyboard, `TAG+="uaccess"`.
It won't take immediate effect, the user will have to unplug/replug the keyboard for this change to take effect. Or you could restart. Or run this command...
```bash
sudo udevadm trigger
```
These commands can be done while the Wootility is running, and it will spring into life.

**Comment by simon-wh** [comment]
This is a known issue on Linux, see: https://wooting.helpscoutdocs.com/article/68-wootility-configuring-device-access-for-wootility-under-linux-udev-rules. Although, using the `uaccess` tag may be a better general approach than the `input` group approach on that page.

The issue is primarily related to the fact that Wootility is distributed using an AppImage, restricting the configuration files like udev rules that can be placed on the system. This is something that's been on the back of my mind to try and improve on the Linux side of things as it's pretty much a required thing to be included, so it should really be there by default.

**Comment by burito** [comment]
In my app, using `hidapi`, while the device will show up in the `hid_enumerate(0,0);` call, the `hid_open(vid, pid, NULL);` call will return `NULL` in this case. I instruct the user to run those commands in my terminal output. Maybe an option?

**Comment by Rocky04** [comment]
It's up to your favor to use groups or the tag...

I'm not so familiar with Linux anyway.

Typically Linux restrict permission on a group base, so by following this approach it makes sense to limit the ability to change the keyboard configuration to a specific selected group only. If I get it right that was the purpose of the input group on old systems anyway.

Maybe this isn't true and I have mixed up some things but the tag thing should provide anyone access and typically you don't want people which are only allowed to remotely connect to the PC access to an input device.

**Comment by simon-wh** [comment]
> Typically Linux restrict permission on a group base, so by following this approach it makes sense to limit the ability to change the keyboard configuration to a specific selected group only. If I get it right that was the purpose of the input group on old systems anyway.
> 
> Maybe this isn't true and I have mixed up some things but the tag thing should provide anyone access but typically you don't want people which are only allowed to remotely connect to the PC access to an input device.

I don't know much about the recommended practices with permissions in cases like these. However, using Steam as a reference, the udev rules provided with Steam for it to be able to access controllers uses the `uaccess` approach. So I feel like it may be alright to have that as the default behaviour

> Due to the fact that this behaviour is intended and part the whole system security concept I wouldn't call that an issue at all. If people want an OS without tweaking so everything works and everyone have the permissions to do everything Windows is the better choice. So I think this shouldn't be handled by the Wootility automatically at all and the better approach would be to provide a message or tip in the Wootility on the startup page with a link to the guide.

Well, it *is* an issue, as the user expects to be able to use Wootility with their keyboard when they install it. Linux may be heavily related to tinkering, but that doesn't mean that you inherently have to tinker if you want to use it, not every user who uses Linux wants to tinker. There are various factors why someone would want to use something that is not Windows and I think it's pretty reasonable for us to at least try and ensure that for *most* people that it'll work as expected out of the box.

**Comment by Rocky04** [comment]
I don't care which udev approach Wooting recommends. I have looked into this just to provide a solution which works and to write a proper guide for it. I don't even use Linux so I'm not up to date which handling is preferred nowadays.

So if the tag thing is used I would recommedn to create a new guide and add a notice to the old one that it's outdated / not recommended and to link the new one because a few more things need to be changed then. In addition I can imagine that then the separated rules for the XInput guide maybe aren't needed anymore.

_I continue the other topic on Discord because that should not be discussed here I guess...._
