### ISSUE TITLE
Profiler Importer - The animation of importing profiles overlaps other profiles

### ISSUE THREAD

**Issue by DarrenVs** [WootingKb/wootility-issues#48]
**Describe the problem**
The animation of importing profiles feels unsettling when there is a profile in the way

**To Reproduce**
1. Create a inactive profile
2. Select a active profile
3. Import a new profile
4. See overlapping text and buttons

**Video/Picture**
![4nlYO94Ptv](https://user-images.githubusercontent.com/2780639/85922434-816f4100-b883-11ea-968a-d76bb8a75362.gif)

---

**Desktop**
 - OS: Windows 10

**Wootility and Firmware versions**
- Firmware: `1.29.1`
- Wootility: `3.5.8-alpha`

**Keyboard Type**
- Wooting One

**Comment by PastaJ36** [comment]
I remember we looked into this. It should be some z-index trickery, but I remember there was an issue. We should look into it again now that everything is a bit more stable.

**Comment by Rocky04** [comment]
Why did the z-index has something to do with it?

I would assume first you need to push the current elements in the list down and then you can insert the new one on the top. Right now it's the opposite and that is the problem.

**Comment by PastaJ36** [comment]
The animation and the list are separate, so I think if we properly place the animation on top of the list it should give the same effect as what you described.

**Comment by Rocky04** [comment]
The problem is the timing not the z-index. The list should move down before the animation is finished not after. Right now there is even a short delay after the animation seems to be finished, until the list is expanted. So changing the z-index makes not a real difference, because who cares if the old first element is shown or the new one until the animation isn't finished.

So as soon as the animations is at the point where it puts the new element on top of the list, the slot should be free. Like to be safe you can first insert a black element on top of the list and then start the animation. In a perfect world there would be two animations perfectly synchronised, one which lowers the list on one element and the other to insert the new one on top.

**Comment by PastaJ36** [comment]
![giphy](https://user-images.githubusercontent.com/7443105/86445891-7305a700-bd13-11ea-9f44-3cec2be5b602.gif)

**Comment by DarrenVs** [comment]
There's still a uneasy ghostly selection box present that doesn't follow the rules of the animation

![r2hkEojIEt](https://user-images.githubusercontent.com/2780639/86515328-6cad2300-be18-11ea-9355-080d00c1e7ea.gif)

Otherwise I'm a fan of the solution

**Comment by PastaJ36** [comment]
Do you mean that the inserted ghost profile at the top gets selected before it gets swapped to the new profile?

**Comment by DarrenVs** [comment]
Whenever there's a profile selected in the Inactive Profiles list; the selection box stays static throughout the animation, not following the rules of the animation.
Plus the animation of importing a profile already contains a selection box, making two appear. Therefore it would probably better if the (ghostly) selection box becomes hidden during the animation, and then reappears on the newly imported and selected profile.

**Comment by Rocky04** [comment]
I agree, the new profile get's the focus anyway so I would also prefer to unselect the last active inactive profile (even it's stills shown).
