### ISSUE TITLE
DKS bindings of the same key on two different profiles causes wrong behavior

### ISSUE THREAD

**Issue by DarrenVs** [WootingKb/wootility-issues#6]
# Wootility Version
3.3.3

# Firmware Version
1.27.3

# Keyboard type
Wooting One

# Issue description
Registering 2 DKS bindings of the same key will cause the previous profile to re-enable the key's non-DKS behavior.

# Steps to reproduce
1. Open Wootility
2. Create 2 active digital profiles with a DKS binding similar to the one below
![image](https://user-images.githubusercontent.com/2780639/70872875-14f9b800-1fab-11ea-97dc-d6035a1570de.png)
3. Open Notepad and test both profiles to see what the result is
4. Notice that one profile has unexpected keystroke behavior

# Pictures / Video of problem
**(Click for video controls)**
[![Click for link to imgur](https://user-images.githubusercontent.com/2780639/70873224-0ca27c80-1fad-11ea-8b95-eea397a0118b.gif)](https://i.imgur.com/gYmJtmO.mp4)
**Result**
**Pressing A in Profile 1*
> AB
> AB

**Pressing A in Profile 2*
> B
> B

**Comment by Rocky04** [comment]
To be precise, this bug don't re-enables the key's non-DKS behavior on the other profies.

If a key is used for DKS which is used on another profile, it will reactivate the original key if it is suppressed via DKS but the binding will still work. Only the last binding will successfully suppress the key.


Like if on profile 3 the A-key is used to only send a "3" and then on profile 1 the A-key is used to only send a "1", then if you switch back to profile 3 the A-key will send the "3" & a "A" were on profile 1 the A-key just sends the "1". If then on profile 2 the A-key is used too to only send a "2", the key will send a "1" & "A" on profile 1 and "3" & "A" on profile 3, where only on profile 2 will just send the "2".

**Comment by Rocky04** [comment]
Maybe this problem is related to the problem from Kim-Lee or he has a different problem (bug) with DKS.

https://discordapp.com/channels/167181566978555904/337667773943775233/673549065417654281

**Comment by Rocky04** [comment]
After a new users has problems with it (https://discordapp.com/channels/167181566978555904/337667773943775233/696285829563285545) I looked into it again.

So in short by swapping profiles only the first DKS binding will be deleted and imported. Meaning if you are creating 4 DKS bindings and then swap that to a blank inactive one, the first DKS is removed but the other 3 are still working. If you then reset all the DKS bindings and swap that inactive to the keyboard again, only the first DKS binding is working and the other three not. If you swap it again and check the JSON data for that profile everything seems to still look good.

**Comment by DarrenVs** [comment]
I do believe more than a hand full of people have ran into this issue without realizing, or reporting it. Purely by possibly not understanding how DKS is supposed function and others not being aware of how the issue occurs.

This problem often causes confusion in the Discord too.
When a user goes into the Discord and asks for help with their DKS bindings, they could end up being proven wrong by other users as on their profile it will end up working just fine (with one profile).
Making the user go through a restore process to "fix" the problem when they just end up avoiding it. This will work until the user creates a second profile with similar bindings, causing new frustration again.
___
This bug has been around since DKS release and in my opinion has been dragged out too long.
It has been a major issue for anyone who uses DKS on more than one profile with similar bindings (having a Overwatch profile and a Apex profile would not allow DKS to function as intended).

### It has stopped me from using DKS do simple things such as:

- Lowering actuation point for a single key such as pressing my ultimate
![image](https://user-images.githubusercontent.com/2780639/78794184-b3bf7f80-79b3-11ea-836a-5012f46330d1.png)
- Unbinding movement keys to respect Analog controls when that profile is active
![image](https://user-images.githubusercontent.com/2780639/78794165-abffdb00-79b3-11ea-8634-e9f3e5dfdc14.png)
- Making a Hold Inventory/Map key when default behavior is a toggle UI key
![image](https://user-images.githubusercontent.com/2780639/78794446-0dc04500-79b4-11ea-8ef4-b0cabb499a16.png)
- Re-binding a key for when the game does not support that button to be used
![image](https://user-images.githubusercontent.com/2780639/78794514-26c8f600-79b4-11ea-9332-ff46ea0e6803.png)

#### Workaround 'solution':
The only workaround for this issue is: having one profile loaded on the Wooting at a time, or being really careful not to have DKS of the same key on 2 or more active profiles.

It should be made clear to the user that Wooting does not fully support using DKS on multiple profiles until this problem or bug has been solved. If the bug is too tasking to solve, maybe a note/message for the user when the they are creating conflicting DKS bindings, warning about the problem ahead.

**Comment by Rocky04** [comment]
**I agree, in the end both problems together make DKS nearly unsuable...**

You can only use one profile if you want to suppress keys and you can't even swap profiles.

**Comment by Rocky04** [comment]
I looked at the stored DKS settings in the inactive profiles and found it very confusing.

Here are the data besides the key actions:
```
{
	...
	"deleteFlag": false,
	"dksIndex": 18,
	"enableDks": true,
	"profileNr": 5
}
```
Because of this structure I assume that the handling where the DKS bindings are saved is handled by the Wootility. Either way this structure makes no sense to be stored together with the profiles in that way.

I get the separation of "deleteFlag" and "enableDks" so DKS can be stored in a profile but inactively even there isn't any switch to do that. But why having "dksIndex" and "profileNr" in it? These two values aren't meaningful to be stored together with the profile. These values are meta values only related for the Wootility for a specific constellation. Meaning they must updated anyway if DKS is changed on another profile.

In additition I don't found any connection between the used "profileNr" and it's profile. Because the DKS storage is decoupled from the profile I get that some assigment must be present in the keyboard, but this can only be a value to identify analog profile one, two or three.


**Or in other words, only the constant data which is needed to be stored in the profile should be stored there for the inactive profiles, so no meta data.**

**Comment by Rocky04** [comment]
_Now about the conclusion..._

I don't know how it's done in the Wooting but I would suggest that the DKS settings have its own memory in the EEPROM. Because of that there must be an assignment for which profile a binding is connected.

So it can look like this (without the actual key bindings):
```cpp
struct DKS
{
	unsigned int deleteFlag : 1;
	unsigned int enableDks : 1;
	unsigned int profileNr : 2;	// enum profileNr { DIGITAL_PROFILE = 0, ANALOG_PROFILE_ONE = 1, ANALOG_PROFILE_TWO = 2, ANALOG_PROFILE_THREE = 3 };
	//... Key bindings
} dks[20];
```
So the access can be done with "dksIndex" like `dks[dksIndex]`. But that variable is only temporary and should not be saved somethere. Instead the Wootiltiy need to scan and hold that everytime a Wooting is connected.

**Comment by Rocky04** [comment]
A workaround to avoid it (at least for the use case described here) is to create some dummy bindings first on the first profile, then the wanted ones. When the dummy bindings are deleted you can successfully bind up to the deleted bindings on the second profile.

So this means the problem is that somehow the Wootility / keyboard got mixed up the index of the combinded overall bindings.
