### ISSUE TITLE
Easier fix for udev rules on Linux

### ISSUE THREAD

**Issue by TjayNL** [WootingKb/wootility-issues#69]
**Describe the bug**
So i had allot of issues with getting the wootility tool working on Linux, so i went to the discord and got this simple solution for somebody in the server. i tried this out and it seems to work way easier then the method on: [udev rules](https://wooting.helpscoutdocs.com/article/68-wootility-configuring-device-access-for-wootility-under-linux-udev-rules)

`
 # Wooting One  
 SUBSYSTEM=="hidraw", ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="ff01", MODE:="0666"
 # Wooting One update mode
 SUBSYSTEM=="hidraw", ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="2402", MODE:="0666"

 # Wooting Two 
 SUBSYSTEM=="hidraw", ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="ff02", MODE:="0666"
 # Wooting Two update mode
 SUBSYSTEM=="hidraw", ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="2403", MODE:="0666"
`

by giving MODE:="0666" and removing GROUP="input" you don't need the extra step of "ensuring that the desired users are in the granted group".

**Comment by Rocky04** [comment]
The udev rules are correct and follow the security principle of Linux to restrict access to just the people who need them. There is no need for all users (the last octet number) as default to provide access to change the config of the Wootings in my opinion.

The only really difference of your suggested changes is the last octet number from zero to six. Due to this all users can access the device not just the user from the the group. So this tells me that if you had problems with the recommended rules, your user wasn't correctly set up to the correct group. The reason why the group should be still present in the rule is so that the created Wooting device get this as the group and not the system standard (root or so).

So I don't recommend to remove the group. This is simple Linux stuff so I expect that users who want to use Linux are aware of how it works or are willing to learn it. Nevertheless a note that the last octet needs to be changed to six in order to provide every user access would maybe a good thing.

**PS: I think more value would be to add how this can be done by using the modern approach of using the tag field instead of the mode and group.**

**Comment by Rocky04** [comment]
So to verify the bahaviour and confirm my assumptions I created a testing group (labeled "test") and used it in the rules as the group name. My interface from the Wooting was named as "hidraw1".

This is the result of the permissions from that specific device node:
```
user@linux-yr97:~> sudo ls -al /dev/hidraw1
crw-rw---- 1 root test 246, 1 29. Okt 16:33 /dev/hidraw1
```

As you can see the owner of the device node is "root" but the group is "test" because of the udev rule. So the permissions are handled the same as anything else in file system. Meaning everyone in that group would have their corresponding permissions (read and write).

**Comment by TjayNL** [comment]
@Rocky04 thank you for your reply, never looked futher that "hey this seems to work so why nog share". again thanks for explaining the pitfalls of my suggested solution.

I'm rather new to Linux so still learning stuff on a daily base ;)

**Comment by Rocky04** [comment]
Just to be complete this is how it's look like if the tag approach is used:
```
user@linux:/home> sudo ls -al /dev/hidraw1
crw-rw----+ 1 root root 246, 1 29. Okt 23:11 /dev/hidraw1
```
The group is still "root" but the rights are handled differently. The "+" at the right end of the permission list indicates that there is an access control list present for that file.

The ACL can be shown with:
```
user@linux:/home> sudo getfacl /dev/hidraw1
getfacl: Entferne führende '/' von absoluten Pfadnamen
# file: dev/hidraw1
# owner: root
# group: root
user::rw-
user:user:rw-
group::---
mask::rw-
other::---
```
The line "user:user:rw-" allow my user labeled "user" to access that device node with read and write permissions.


The whole udev rule ("/etc/udev/rules.d/69-wooting.rules", _don't forget the prefix file number_) looks lite this:
```
# Wooting One  
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="ff01", TAG+="uaccess"
# Wooting One update mode 
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="2402", TAG+="uaccess"

# Wooting Two 
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="ff02", TAG+="uaccess"
# Wooting Two update mode  
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="2403", TAG+="uaccess"
```
