### ISSUE TITLE
Feature Request: Disable DirectInput switch in Wootility

### ISSUE THREAD

**Issue by Brionac95** [WootingKb/wootility-issues#74]
I would like to suggest a feature to **disable the keyboard DirectInput interface inside Wootility**, just like it has already been done with XInput.

The reason for this request is that some games still pick up DirectInput devices, and for those who want to use the keyboard only as a normal keyboard it could fill up controller slots for said games. It would also come handy for those that only use Analog profiles for just a handful of games. Also, considering that there is a known issue for [too many controllers recognized by Windows upon connecting the Wooting Keyboard](https://wooting.helpscoutdocs.com/article/56-fix-controller-settings-under-windows), for said games just the keyboard could fill up all the controller slots available, making it impossible to use the keyboard and a DirectInput controller at the same time.

Alternatively, a function to disable the whole Analog Interface of the keyboard could be a possibility, but probably having more options for each interface is better.

**Comment by Rocky04** [comment]
Related to: https://github.com/WootingKb/wootility-issues/issues/31

**Comment by Rocky04** [comment]
I'm strongly recommend to change the whole XInput, DirectInput handling within the settings menu if this feature is considered to be implemented. So to have a three way switch instead of a separate switch for XInput and DirectInput.

Reasons why:
1. Due to the same name for DirectInput the user can't differ them in a game which only supports DirectInput and sometimes it's not possible to pick the correct one.
2. All DirectInput interfaces are typically ignored anyway as soon as a game detects the XInput interface. So the classic controller part then can't be used anymore as soon as the Xbox controller part is enabled.
3. If the recommendation is followed to have a different product and vendor ID for the device it helps to limit the needed amount to just three. Also otherwise Steam would most likely block the classic controller again and **this is the main reason why the problem described above even exist.** But if the IDs are correctly differ Steam would show the classic gamepad of the Wooting again.


So again, as discussed multiple times by now, the problem isn't the presence of the DirectInput interfaces of the Wooting. The problem exists due to the interface changes while the same IDs are used (so that the games think multiple controllers are present) and because Steam blocks the classic gamepad of the Wooting (so they can't be disabled within Steam so game can pick them up as Xbox controller).

**Comment by Brionac95** [comment]
I agree with adding a single option with a three way switch for disabling XInput, DirectInput, or both, seems like a better idea for me.

As far as the issue with the wrong controllers assignment, I tried to disable the DirectInput interface of the keyboard and then re-enabling it again and at least on my end it isn't recognizing the interface two times when I re-enable it. Though the problem still exists, so yeah I think a simple switch couldn't solve the issue completely. I guess the switch should be implemented along with the existent registry fix, so that everytime you disable the interface it shouldn't generate more controller entries in the registry fix. But still, DirectInput devices are still recognized by some games by default, so completely excluding the possibility to implement a switch wouldn't be a really wise choice. The more options, the better.

**Comment by DarrenVs** [comment]
I don't agree with the design that the Wooting can take up two gamepad slots at once.

Options to disable either Xinput or DirectInput would help solve a lot of issues, but I do not think users or games should be running into problems like this to begin with.

Most games, and Windows say that each connected device to be an individual device. Because of this old convention, the gamepad slots are decided in the order you connect the gamepads in. But for the Wooting it would decided at random each time you connect it as it can attempt to load two gamepads at once.

Having the ability to load two gamepads, which you can only control one of at a time, can only cause unexpected issues for the user and game.
Any game that expects Gamepad 1 to be the primary(Player1) gamepad would only work by chance, and any game that allows Local Multiplayer will only work right if it the game can alter which Gamepad is which player.

---

So I also believe that the three way switch would be the best solution as that would avoid the design problems for the user and games.

**Pick input method:**
- [x] Xinput > *(default setting)*
- [ ] DirectInput
- [ ] Disable Gamepad

**Comment by PastaJ36** [comment]
I like this, will also make it a little clearer in the UI. We can either show xinput bindings, dinput bindings or grey out

**Comment by PastaJ36** [comment]
This will be added to 3.6. We're testing in alpha now, should be in public beta later this week
