### ISSUE TITLE
Remove fn on both layers when you unbind

### ISSUE THREAD

**Issue by PastaJ36** [WootingKb/wootility-issues#81]
**Describe the bug**
When you remove FN keybinding on second layer it will remain on the first layer

**Comment by Rocky04** [comment]
By the way, it's also the same the other way around.

But please keep the behavior to put the Fn lock on the same key on the secondary layer to create it as a toggle without removing the Fn key on the primary layer.

**Comment by DarrenVs** [comment]
I actually make use of this bug a lot on my keyboard and I think it's a great feature!

I unbind Fn on the Function layer, bind Alt_Gr in that place, and then bind numlock keys on the number row on my Wooting One allowing me to enter Alt-Codes with a Wooting One by only pressing Fn + number keys
![image](https://user-images.githubusercontent.com/2780639/106757263-6d1ccf00-6630-11eb-9bb0-ea75df205f43.png)

Another feature this bug brings in gaming is that you can use the Fn key as a modifier key in games while still having the Fn key do a keypress itself for example, putting Fn on Alt, and putting Alt in the Function layer where Fn is. modifying every key around WASD(movement keys) to perform a different keypress than the main layer, giving you more keybinds under the same area of the keyboard (examples: E to throw grenade and Alt+E to open inventory, or F to melee and Alt+F for a voice command). This setup would for example still allow the user to press Alt+Tab even though the Fn key is on the Alt key.
![tTAu5062kt](https://user-images.githubusercontent.com/2780639/106758427-c5a09c00-6631-11eb-810b-ef2cce82146d.gif)
This can be very useful for games that have a large amount of keybinds like a MMO such as World of Warcraft, Shooter games such as Arma 3, or space game such as Elite Dangerous

---

I propose that the Fn key doesn't automatically get mapped on the Function Layer to promote this use case.
For the Lekker/HE keyboard with more memory, this could even allow multiple function layers, or have them bound to specific profiles.

**Comment by Rocky04** [comment]
Arma and WoW take use of Alt to enter a different layer? So far I haven't played any game which have this.

**Comment by DarrenVs** [comment]
I use this feature mainly in Apex to quickly select one out of my 8 different healing gear options without having to extend my finger to the far right side of the keyboard
And in Overwatch to do a quick callout for any voice line such as "I need healing", Ult Charge status, "Group up command", "Attack now", etc..

**Comment by Rocky04** [comment]
Of course a lot of games can differ between normal keys and num pad keys but games which support layers by the modifier keys are rare.

So I still don't know if that works because the games you mentioned support this or if this is just woorking because of the num pad keys and so that Alt don't do anything in that case.

**Comment by DarrenVs** [comment]
In the example I've used numpad keys as that has seemed to work for me and doesn't overlap with any of the other Wooting One keys, but they do not have to be numpad keys if that doesn't work. Neither does it have to be on the Alt key, it could be hidden under the Tab key if that is more compatible with the game engine

**Comment by Rocky04** [comment]
But than your second example has nothing to do with the topic to support a different key on the secondary layer where the Fn key is on the primary.

**Comment by DarrenVs** [comment]
Video example of 'example 2':
![Uu7ymwOvDG](https://user-images.githubusercontent.com/2780639/106771309-1c60a280-663f-11eb-9f7f-fb8a61ec9fd5.gif)

It's just like having Fn on the Alt key, but instead you do it under the Tab key. The only difference between example 1 and example 2 is Tab isn't a modifier key in Windows. You get the exact same behaviour if you were to use this in your games.

**Comment by DarrenVs** [comment]
> Did you wanna say that you want to preserve the original function of the key which you also want to use to access the secondary layer?

Correct
I love this unintended feature of the Fn key. It brings a whole new depth on how you can use the Function Layer, and I would love to see more of it if it was possible on the Wooting One/Two.

Being able to re-bind the Fn key in the Function Layer allows you to practically **disguise it** as a "Alt Layer" or a "Ctrl Layer", or in the example above, even add a 'Tab Layer' instead of 'Function Layer'.

---

I'm sure there aren't many who use the Function Layer this way, or expect you can do things like this with the Function Layer, but I always dreamed of a keyboard that could do this.
I have a bunch more ideas for a better implementation of this 'feature' that would be more intuitive. But I doubt I can describe it well in text.
Holding Shift modifies Analog curve)
(Holding

**Comment by Rocky04** [comment]
**Hmm, I have mixed feelings on this because the things / use cases you want are maybe better placed within a proper macro support which may will come some day.**

**Comment by DarrenVs** [comment]
**I don't think using the Function Layer for gaming instead of just functions is hacky. I think it's a innovative tool for the user to create efficient keybindings.**
The remapping tool has so much potential and I like to believe that using it for games is one way of complimenting it.

_Even if this bug becomes fixed, I would just swap my Alt key with the Fn key (the intended way) making it a slight inconvenience to use my keyboard when I'm not playing games._

---

I do agree that there could be a way better implementation of a feature like this, and would love to see a replacement that attaches to the keyboard's profile.

**Comment by Rocky04** [comment]
It's not that your idea is bad it's just that you can't have an intuitive Fn handling and this behavior.

As I already mentioned it should be always possible to temporary leave a locked secondary layer and for this you need a Fn key there. And for usability it should be on the same spot. Of course if the Fn lock key is bound to that spot Fn can be missed.

_Then the only suitable way for your use case would be if there is no Fn lock key present on the Fn layer._

**Comment by simon-wh** [comment]
Should be resolved in Wootility v4.3
